language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -y install python-software-properties
  - sudo add-apt-repository -y ppa:mnunberg/cmake
  - sudo apt-get update
  - sudo apt-get -y install libgtest-dev libssl-dev libev-dev libevent-dev cmake

script: |
  ./cmake/configure --enable-debug --disable-couchbasemock && make && make alltests && cd build && \
  (ctest -V || (cat check*.log; false))

notifications:
  email:
    - stephen.tunney@gmail.com
