INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(SNAPPY snappy)
IF(SNAPPY_FOUND)
  SET(SNAPPY_INCLUDES ${SNAPPY_INCLUDE_DIRS})
  SET(LCB_SNAPPY_PKG_VERSION ${SNAPPY_VERSION})
ELSE()
  FIND_PATH(SNAPPY_INCLUDES snappy-c.h
    HINTS ENV SNAPPY_DIR ${SNAPPY_DIR}
    PATH_SUFFIXES include)
  FIND_LIBRARY(SNAPPY_LIBRARIES NAMES snappy
    HINTS ENV SNAPPY_DIR ${SNAPPY_DIR}
    PATH_SUFFIXES lib)
  IF(SNAPPY_LIBRARIES AND SNAPPY_INCLUDES)
    SET(SNAPPY_FOUND TRUE)
  ELSE()
    SET(SNAPPY_FOUND FALSE)
  ENDIF()
ENDIF()
