IF(SNAPPY_ROOT_DIR)
  FIND_PATH(SNAPPY_INCLUDES snappy-c.h
    PATHS ${SNAPPY_ROOT_DIR}
    PATH_SUFFIXES include
    NO_DEFAULT_PATH)
  FIND_LIBRARY(SNAPPY_LIBRARIES NAMES snappy
    PATHS ${SNAPPY_ROOT_DIR}
    PATH_SUFFIXES lib
    NO_DEFAULT_PATH)
  IF(SNAPPY_LIBRARIES AND SNAPPY_INCLUDES)
    SET(SNAPPY_FOUND TRUE)
    MESSAGE(STATUS "Found libsnappy in ${SNAPPY_LIBRARIES}")
  ELSE()
    SET(SNAPPY_FOUND FALSE)
  ENDIF()
ELSE()
  INCLUDE(FindPkgConfig)
  PKG_CHECK_MODULES(SNAPPY snappy)
  IF(SNAPPY_FOUND)
    SET(SNAPPY_INCLUDES ${SNAPPY_INCLUDE_DIRS})
    SET(LCB_SNAPPY_PKG_VERSION ${SNAPPY_VERSION})
    MESSAGE(STATUS "Found libsnappy in ${SNAPPY_LIBDIR} (found version \"${SNAPPY_VERSION}\")")
  ELSE()
    FIND_PATH(SNAPPY_INCLUDES snappy-c.h PATH_SUFFIXES include)
    FIND_LIBRARY(SNAPPY_LIBRARIES NAMES snappy PATH_SUFFIXES lib)
    IF(SNAPPY_LIBRARIES AND SNAPPY_INCLUDES)
      SET(SNAPPY_FOUND TRUE)
      MESSAGE(STATUS "Found libsnappy in ${SNAPPY_LIBRARIES}")
    ELSE()
      SET(SNAPPY_FOUND FALSE)
    ENDIF()
  ENDIF()
ENDIF()
